### ISSUE TITLE
Telekom Malaysia Evaluation: No module named 'csvimport'

### ISSUE THREAD

**Issue by afaideen** [afifnizam/Afif_DjangoApp#1]
Hi i executed python manage.py runserver. I got following error,

E:\Downloads\email\Afif_DjangoApp-master\Afif_DjangoApp-master>python manage.py
runserver
Unhandled exception in thread started by <function check_errors.<locals>.wrapper
 at 0x0000004DCCFD02F0>
Traceback (most recent call last):
  File "C:\Python35\lib\site-packages\django\utils\autoreload.py", line 228, in
wrapper
    fn(*args, **kwargs)
  File "C:\Python35\lib\site-packages\django\core\management\commands\runserver.
py", line 117, in inner_run
    autoreload.raise_last_exception()
  File "C:\Python35\lib\site-packages\django\utils\autoreload.py", line 251, in
raise_last_exception
    six.reraise(*_exception)
  File "C:\Python35\lib\site-packages\django\utils\six.py", line 685, in reraise

    raise value.with_traceback(tb)
  File "C:\Python35\lib\site-packages\django\utils\autoreload.py", line 228, in
wrapper
    fn(*args, **kwargs)
  File "C:\Python35\lib\site-packages\django\__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Python35\lib\site-packages\django\apps\registry.py", line 85, in popu
late
    app_config = AppConfig.create(entry)
  File "C:\Python35\lib\site-packages\django\apps\config.py", line 120, in creat
e
    mod = import_module(mod_path)
  File "C:\Python35\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 985, in _gcd_import
  File "<frozen importlib._bootstrap>", line 968, in _find_and_load
  File "<frozen importlib._bootstrap>", line 943, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 985, in _gcd_import
  File "<frozen importlib._bootstrap>", line 968, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
ImportError: No module named 'csvimport'

**Comment by afifnizam** [comment]
i forgot to mentioned that you have to install csv import by doing -> pip install csvimport . through the command line in the project directory

**Comment by afaideen** [comment]
ok now it returns another error,

E:\Downloads\email\Afif_DjangoApp-master\Afif_DjangoApp-master>python manage.py runserver
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Python34\lib\site-packages\django\core\management\__init__.py", line
350, in execute_from_command_line
    utility.execute()
  File "C:\Python34\lib\site-packages\django\core\management\__init__.py", line
342, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Python34\lib\site-packages\django\core\management\__init__.py", line
176, in fetch_command
    commands = get_commands()
  File "C:\Python34\lib\functools.py", line 448, in wrapper
    result = user_function(*args, **kwds)
  File "C:\Python34\lib\site-packages\django\core\management\__init__.py", line
71, in get_commands
    for app_config in reversed(list(apps.get_app_configs())):
  File "C:\Python34\lib\site-packages\django\apps\registry.py", line 137, in get
_app_configs
    self.check_apps_ready()
  File "C:\Python34\lib\site-packages\django\apps\registry.py", line 124, in che
ck_apps_ready
    raise AppRegistryNotReady("Apps aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.

**Comment by afifnizam** [comment]
ok could you please abort running the server by pressing control+c

1.  try run this command -> python manage.py migrate

2.  then run the -> python manage.py

**Comment by afaideen** [comment]
now it returns back error--> ImportError: No module named 'csvimport'. When running 'pip csvimport' i got following error,
Collecting csvimport
  Could not find a version that satisfies the requirement csvimport (from versio
ns: )
No matching distribution found for csvimport

**Comment by afifnizam** [comment]
i am sorry , the command is as shown here -> pip install django-csvimport

**Comment by afaideen** [comment]
Please correct in the readme

**Comment by afaideen** [comment]
Now still with error below,
E:\Downloads\email\Afif_DjangoApp-master\Afif_DjangoApp-master>python manage.py
migrate
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Python34\lib\site-packages\django\core\management\__init__.py", line
350, in execute_from_command_line
    utility.execute()
  File "C:\Python34\lib\site-packages\django\core\management\__init__.py", line
324, in execute
    django.setup()
  File "C:\Python34\lib\site-packages\django\__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Python34\lib\site-packages\django\apps\registry.py", line 85, in popu
late
    app_config = AppConfig.create(entry)
  File "C:\Python34\lib\site-packages\django\apps\config.py", line 90, in create

    module = import_module(entry)
  File "C:\Python34\lib\importlib\__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2224, in _find_and_load_unlocked
ImportError: No module named 'import_export'

**Comment by afifnizam** [comment]
sure i will do it now

**Comment by afifnizam** [comment]
I have managed to host the app through this link
http://afifnizam.pythonanywhere.com/

However, there are still changes needed to be made on the gui. Some of the
icons and pictures are still yet to be displayed

**Comment by afaideen** [comment]
Running error in my machine. Had you compiled it successful, you can video it for my viewing purpose as part of evaluation.

**Comment by afaideen** [comment]
can you give me the link python installer 3.4 that you used?

**Comment by afifnizam** [comment]
yes sure here is the link :
https://www.python.org/ftp/python/3.5.4/python-3.5.4-amd64.exe

**Comment by afaideen** [comment]
you used python35 not 34

**Comment by afifnizam** [comment]
yes when i  installed python the folder appeared as python 34. thats why i
had to use python34

**Comment by afaideen** [comment]
always got ImportError: No module named import_export although csvimport installed with success.

**Comment by afifnizam** [comment]
have you seen the video i sent to mr alfi?


https://drive.google.com/file/d/0B3ooV_aV_yPwamlPNDkwM1V3YlU/view?usp=sharing

everything seems fine.

in the mean time, i may have to check with importexport error

**Comment by afaideen** [comment]
yes from your video it works.

**Comment by afifnizam** [comment]
can you try putting this command ?
pip install django-import-export
